### ISSUE TITLE
This repository embeds some proprietary images

### ISSUE THREAD

**Issue by CelesteBlue-dev** [gnuton/PSVIta#14]
https://github.com/gnuton/PSVIta/blob/master/hello_cpp_world/assets/spr/img_splash.png

You can't use Homebrew Browser by @devnoname120 without precising that you are authorized by the author.

**Comment by devnoname120** [comment]
@CelesteBlue-dev I don't mind.

**Comment by gnuton** [comment]
Hi Celeste. I m gonna remove all VHBB artwork ASAP. That s there as
placeholder since the initial code was taken by vhbb, and devniname knows
what that.
Thanks for reporting btw.

**Comment by CelesteBlue-dev** [comment]
Don't spend time on this little issue. Good contnuation.
